changelog:
  exclude:
    labels:
      - ignore-for-release
      - chore
  categories:
    - title: Features
      labels:
        - feat
        - feature
        - enhancement
    - title: Bug Fixes
      labels:
        - fix
        - bug
    - title: Performance
      labels:
        - perf
        - performance
        - optimization
    - title: Documentation
      labels:
        - docs
        - documentation
    - title: Other
      labels:
        - "*"
