//! Rule-table integration correctness (0.27.0).
//!
//! Deterministic 100-case sample across the rule families A–H (powers and
//! binomials, exponentials/logarithms, trigonometry, hyperbolic functions,
//! inverse trig/hyperbolic, rational intercepts, radicals, special forms).
//! Every case is verified against SymPy's `integrate` (skipped gracefully
//! when `uv` is unavailable), so a wrong antiderivative fails the test
//! regardless of which pipeline stage produced it.
//!
//! The sample is generated by a fixed-seed PRNG (SplitMix64, seed 1892) so
//! the case list is reproducible; cases that the engine cannot solve at all
//! would fail the SymPy comparison and must be removed rather than
//! weakened — the generator only draws from families the rules cover.

/// Deterministic PRNG (SplitMix64), matching the corpus fetch script's
/// sampling convention.
struct SplitMix64(u64);

impl SplitMix64 {
    fn next_u64(&mut self) -> u64 {
        self.0 = self.0.wrapping_add(0x9E37_79B9_7F4A_7C15);
        let mut z = self.0;
        z = (z ^ (z >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
        z ^ (z >> 31)
    }

    /// Uniform integer in `[lo, hi]` (inclusive).
    fn range(&mut self, lo: i64, hi: i64) -> i64 {
        lo + (self.next_u64() % (hi - lo + 1) as u64) as i64
    }
}

/// Generate the 100-case sample as (integrand, var) pairs.
fn sample_cases() -> Vec<(String, &'static str)> {
    let mut rng = SplitMix64(1892);
    let mut cases: Vec<(String, &'static str)> = Vec::new();

    let add = |cases: &mut Vec<(String, &'static str)>, s: &str| {
        cases.push((s.to_string(), "x"));
    };

    // A. Powers / binomials (12 cases)
    for _ in 0..4 {
        let n = rng.range(2, 6);
        add(&mut cases, &format!("x^{n}"));
    }
    for _ in 0..4 {
        let (a, b, n) = (rng.range(1, 3), rng.range(1, 3), rng.range(2, 4));
        add(&mut cases, &format!("({a}+{b}*x)^{n}"));
    }
    for _ in 0..4 {
        let (m, n) = (rng.range(1, 4), rng.range(1, 3));
        add(
            &mut cases,
            &format!("x^{m}*({}*x+{})^{n}", rng.range(1, 2), rng.range(1, 3)),
        );
    }

    // B. Exponentials / logarithms (16 cases)
    for _ in 0..3 {
        let (n, a) = (rng.range(1, 3), rng.range(1, 2));
        add(&mut cases, &format!("x^{n}*exp({a}*x)"));
    }
    for _ in 0..3 {
        let (m, n) = (rng.range(0, 2), rng.range(2, 3));
        add(&mut cases, &format!("x^{m}*log(x)^{n}"));
    }
    for _ in 0..3 {
        let (a, b) = (rng.range(1, 2), rng.range(1, 3));
        add(&mut cases, &format!("exp({a}*x)*sin({b}*x)"));
    }
    for _ in 0..3 {
        let (a, b) = (rng.range(1, 2), rng.range(1, 3));
        add(&mut cases, &format!("exp({a}*x)*cos({b}*x)"));
    }
    for _ in 0..2 {
        let n = rng.range(2, 4);
        add(&mut cases, &format!("log(x)^{n}"));
    }
    add(&mut cases, "1/(x*log(x))");
    add(&mut cases, "x*exp(-x^2)");

    // C. Trigonometry (24 cases)
    for _ in 0..3 {
        let n = rng.range(2, 5);
        add(&mut cases, &format!("sin(x)^{n}"));
    }
    for _ in 0..3 {
        let n = rng.range(2, 5);
        add(&mut cases, &format!("cos(x)^{n}"));
    }
    for _ in 0..2 {
        let n = rng.range(2, 4);
        add(&mut cases, &format!("tan(x)^{n}"));
    }
    for _ in 0..2 {
        let n = rng.range(2, 4);
        add(&mut cases, &format!("sec(x)^{n}"));
    }
    add(&mut cases, "cot(x)^3");
    add(&mut cases, "csc(x)^3");
    for _ in 0..4 {
        let (m, n) = (rng.range(1, 4), rng.range(1, 4));
        // At least one odd exponent so the rules' odd-power peel applies.
        let (m, n) = if m % 2 == 0 && n % 2 == 0 {
            (m + 1, n)
        } else {
            (m, n)
        };
        add(&mut cases, &format!("sin(x)^{m}*cos(x)^{n}"));
    }
    for _ in 0..3 {
        let (a, b) = (rng.range(1, 3), rng.range(1, 3));
        if a == b {
            continue;
        }
        match rng.range(0, 2) {
            0 => add(&mut cases, &format!("sin({a}*x)*sin({b}*x)")),
            _ => add(&mut cases, &format!("cos({a}*x)*cos({b}*x)")),
        }
    }
    for _ in 0..2 {
        let (a, b) = (rng.range(1, 3), rng.range(1, 3));
        if a == b {
            continue;
        }
        add(&mut cases, &format!("sin({a}*x)*cos({b}*x)"));
    }

    // D. Hyperbolic (12 cases)
    for _ in 0..2 {
        let n = rng.range(2, 4);
        add(&mut cases, &format!("sinh(x)^{n}"));
    }
    for _ in 0..2 {
        let n = rng.range(2, 4);
        add(&mut cases, &format!("cosh(x)^{n}"));
    }
    for _ in 0..2 {
        let n = rng.range(2, 4);
        add(&mut cases, &format!("tanh(x)^{n}"));
    }
    add(&mut cases, "coth(x)^3");
    add(&mut cases, "sech(x)^3");
    add(&mut cases, "csch(x)^3");
    for _ in 0..4 {
        match rng.range(0, 3) {
            0 => add(&mut cases, &format!("sinh({}*x+1)", rng.range(1, 2))),
            1 => add(&mut cases, &format!("cosh({}*x+1)", rng.range(1, 2))),
            2 => add(&mut cases, &format!("tanh({}*x+1)", rng.range(1, 2))),
            _ => add(&mut cases, &format!("coth({}*x+1)", rng.range(1, 2))),
        }
    }

    // E. Inverse trig / hyperbolic (8 cases)
    add(&mut cases, "asin(x)");
    add(&mut cases, "acos(x)");
    add(&mut cases, "atan(x)");
    add(&mut cases, "asinh(x)");
    add(&mut cases, "acosh(x)");
    add(&mut cases, "atanh(x)");
    add(&mut cases, "x*atan(x)");
    add(&mut cases, "x*asin(x)");

    // F. Rational intercepts (6 cases)
    for _ in 0..2 {
        let a = rng.range(1, 3);
        add(&mut cases, &format!("1/({}^2+x^2)", a));
    }
    for _ in 0..2 {
        let a = rng.range(1, 3);
        add(&mut cases, &format!("1/({}^2-x^2)", a));
    }
    for _ in 0..2 {
        let (a, b) = (rng.range(1, 3), rng.range(1, 2));
        add(&mut cases, &format!("x/({a}+{b}*x^2)"));
    }

    // G. Radicals (12 cases; numeric parameters so SymPy can prove the
    // sqrt identities without branch/assumption handling)
    for _ in 0..2 {
        let (a, b) = (rng.range(1, 3), rng.range(1, 2));
        add(&mut cases, &format!("sqrt({a}+{b}*x)"));
    }
    for _ in 0..2 {
        let (a, b) = (rng.range(1, 3), rng.range(1, 2));
        add(&mut cases, &format!("1/sqrt({a}+{b}*x)"));
    }
    for _ in 0..2 {
        let (a, b) = (rng.range(1, 3), rng.range(1, 2));
        add(&mut cases, &format!("x/sqrt({a}+{b}*x)"));
    }
    add(&mut cases, "sqrt(4-x^2)");
    add(&mut cases, "1/sqrt(4-x^2)");
    add(&mut cases, "1/sqrt(x^2+4)");
    add(&mut cases, "1/sqrt(x^2 - 4)");
    add(&mut cases, "sqrt(x^2+4)");
    add(&mut cases, "sqrt(x^2 - 4)");

    // H. Special forms (10 cases)
    add(&mut cases, "x*sin(x^2)");
    add(&mut cases, "x*cos(x^2)");
    add(&mut cases, "x*sinh(x^2)");
    add(&mut cases, "x*cosh(x^2)");
    add(&mut cases, "exp(-x^2)");
    add(&mut cases, "exp(x)/x");
    add(&mut cases, "sin(x)/x");
    add(&mut cases, "cos(x)/x");
    add(&mut cases, "sin(x^2)");
    add(&mut cases, "cos(x^2)");

    // Top up to exactly 100 cases deterministically (the seeded part may
    // skip product-to-sum pairs with equal frequencies).
    let pad = [
        "sin(x)^2",
        "cos(x)^3",
        "tan(x)^2",
        "log(x)^2",
        "x^2*exp(x)",
        "sqrt(1+x)",
        "1/sqrt(1+x)",
        "x*exp(x)",
        "sin(2*x)",
        "cos(3*x)",
    ];
    let mut i = 0;
    while cases.len() < 100 {
        add(&mut cases, pad[i % pad.len()]);
        i += 1;
    }
    cases.truncate(100);
    cases
}

#[test]
fn integral_rules_sample_vs_sympy() {
    let cases = sample_cases();
    assert_eq!(cases.len(), 100, "sample must have exactly 100 cases");
    for (idx, (integrand, var)) in cases.iter().enumerate() {
        let result = crate::integrate_to_string(integrand, var);
        assert!(
            !result.contains("Integral("),
            "case {idx} ({integrand}) unsolved: {result}"
        );
        crate::assert_eq_sympy(&result, "integrate", integrand);
    }
}
