/* oCAS C API */

#ifndef OCAS_H
#define OCAS_H

/* Generated with cbindgen:0.28.0 */

/* Warning: this file is auto-generated by cbindgen. Do not modify. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Success error code.
 */
#define ocas_OCAS_OK 0

/**
 * A null pointer was passed where a non-null pointer was required.
 */
#define ocas_OCAS_ERROR_NULL_POINTER 1

/**
 * An operation failed inside the oCAS runtime.
 */
#define ocas_OCAS_ERROR_RUNTIME 2

/**
 * A string could not be parsed as a valid expression.
 */
#define ocas_OCAS_ERROR_PARSE 3

/**
 * An argument had an unexpected type or value.
 */
#define ocas_OCAS_ERROR_INVALID_ARGUMENT 4

/**
 * A division by zero or similar undefined operation was attempted.
 */
#define ocas_OCAS_ERROR_DIVISION_BY_ZERO 5

/**
 * Memory allocation failed.
 */
#define ocas_OCAS_ERROR_OUT_OF_MEMORY 6

/**
 * Opaque expression handle. Each handle owns its arena; use
 * [`ocas_expr_free`] to release it.
 */
struct ocas_OcasExpr {
  uint8_t _private[0];
};

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Return the oCAS version string.
 *
 * The returned pointer is valid for the lifetime of the program and must
 * not be freed by the caller.
 */
const char *ocas_version(void);

/**
 * Return the message for the last error on the calling thread, or `NULL`
 * if no error has occurred.
 *
 * The returned string is owned by the library and must not be freed or
 * modified by the caller. It remains valid until the next call that sets
 * an error on the same thread or until [`ocas_error_clear`] is called.
 */
const char *ocas_error_last_message(void);

/**
 * Clear the last error on the calling thread.
 */
void ocas_error_clear(void);

/**
 * Parse `input` into a new expression handle.
 *
 * Returns `NULL` on failure; use [`ocas_error_last_message`](crate::ocas_error_last_message)
 * to retrieve the error message. On success, `*err_out` (if non-null) is
 * set to [`OCAS_OK`](crate::OCAS_OK).
 *
 * # Safety
 *
 * `input` must be a valid null-terminated C string. `err_out` if non-null
 * must point to writable memory.
 */
struct ocas_OcasExpr *ocas_expr_parse(const char *input, int *err_out);

/**
 * Free an expression handle. Passing `NULL` is a no-op.
 *
 * # Safety
 *
 * `handle` must be either null or a pointer returned by a function in this
 * module, and must not have been freed already.
 */
void ocas_expr_free(struct ocas_OcasExpr *handle);

/**
 * Clone an expression into a new arena.
 *
 * # Safety
 *
 * `handle` must be a valid non-null expression handle.
 */
struct ocas_OcasExpr *ocas_expr_clone(const struct ocas_OcasExpr *handle, int *err_out);

/**
 * Render `handle` to a null-terminated C string.
 *
 * The returned string is heap-allocated and owned by the caller. Release it
 * with [`ocas_string_free`]. Returns `NULL` on failure.
 *
 * # Safety
 *
 * `handle` must be a valid non-null expression handle.
 */
char *ocas_expr_to_string(const struct ocas_OcasExpr *handle, int *err_out);

/**
 * Free a string returned by [`ocas_expr_to_string`]. Passing `NULL` is a
 * no-op.
 *
 * # Safety
 *
 * `s` must be either null or a pointer returned by [`ocas_expr_to_string`],
 * and must not have been freed already.
 */
void ocas_string_free(char *s);

/**
 * Re-normalize `handle` in place.
 *
 * # Safety
 *
 * `handle` must be a valid non-null expression handle.
 */
int ocas_expr_normalize(struct ocas_OcasExpr *handle, int *err_out);

/**
 * Differentiate `handle` with respect to `var`. Returns a new expression
 * handle (caller owns it) or `NULL` on failure.
 *
 * # Safety
 *
 * `handle` must be a valid non-null expression handle. `var` must be a
 * valid null-terminated C string.
 */
struct ocas_OcasExpr *ocas_expr_diff(const struct ocas_OcasExpr *handle,
                                     const char *var,
                                     int *err_out);

/**
 * Integrate `handle` with respect to `var`. Returns a new expression handle
 * or `NULL` on failure. If the integral cannot be solved analytically, the
 * result is the unevaluated form `Integral(expr, var)`.
 *
 * # Safety
 *
 * See [`ocas_expr_diff`].
 */
struct ocas_OcasExpr *ocas_expr_integrate(const struct ocas_OcasExpr *handle,
                                          const char *var,
                                          int *err_out);

/**
 * Compute the Taylor series of `handle` around `point` up to `order`.
 *
 * # Safety
 *
 * `handle` and `point` must be valid non-null expression handles. `var`
 * must be a valid null-terminated C string.
 */
struct ocas_OcasExpr *ocas_expr_taylor(const struct ocas_OcasExpr *handle,
                                       const char *var,
                                       const struct ocas_OcasExpr *point,
                                       uint32_t order,
                                       int *err_out);

/**
 * Simplify `handle` using the default rule set. Returns a new expression
 * handle or `NULL` on failure.
 *
 * # Safety
 *
 * `handle` must be a valid non-null expression handle.
 */
struct ocas_OcasExpr *ocas_expr_simplify(const struct ocas_OcasExpr *handle, int *err_out);

/**
 * Substitute every occurrence of `var` in `handle` with `replacement`.
 *
 * # Safety
 *
 * `handle` and `replacement` must be valid non-null expression handles.
 * `var` must be a valid null-terminated C string.
 */
struct ocas_OcasExpr *ocas_expr_substitute(const struct ocas_OcasExpr *handle,
                                           const char *var,
                                           const struct ocas_OcasExpr *replacement,
                                           int *err_out);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* OCAS_H */
