/* oCAS C API */

#ifndef OCAS_H
#define OCAS_H

/* Generated with cbindgen:0.29.4 */

/* Warning: this file is auto-generated by cbindgen. Do not modify. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Success error code.
 */
#define ocas_OCAS_OK 0

/**
 * A null pointer was passed where a non-null pointer was required.
 */
#define ocas_OCAS_ERROR_NULL_POINTER 1

/**
 * An operation failed inside the oCAS runtime.
 */
#define ocas_OCAS_ERROR_RUNTIME 2

/**
 * A string could not be parsed as a valid expression.
 */
#define ocas_OCAS_ERROR_PARSE 3

/**
 * An argument had an unexpected type or value.
 */
#define ocas_OCAS_ERROR_INVALID_ARGUMENT 4

/**
 * A division by zero or similar undefined operation was attempted.
 */
#define ocas_OCAS_ERROR_DIVISION_BY_ZERO 5

/**
 * Memory allocation failed.
 */
#define ocas_OCAS_ERROR_OUT_OF_MEMORY 6

/**
 * Opaque expression handle. Each handle owns its arena; use
 * [`ocas_expr_free`] to release it.
 */
struct ocas_OcasExpr {
  uint8_t _private[0];
};

/**
 * Opaque handle for a bivariate integer polynomial.
 */
struct ocas_OcasPolyZ {
  uint8_t _private[0];
};

/**
 * A factor returned by [`ocas_poly_z_factor`] or [`ocas_poly_fp_factor`].
 *
 * The `poly` pointer is a generic `void*`; the caller must cast it to the
 * appropriate concrete type depending on which factorization function was
 * used (`OcasPolyZ*` for Z, `OcasPolyFp*` for Fp). Each returned polynomial
 * handle must be freed with the corresponding type-specific free function.
 */
struct ocas_OcasPolyFactor {
  /**
   * The polynomial factor. The actual type is determined by the caller.
   */
  void *poly;
  /**
   * Multiplicity of the factor.
   */
  size_t multiplicity;
};

/**
 * An array of factors returned by [`ocas_poly_z_factor`] or
 * [`ocas_poly_fp_factor`]. Free with [`ocas_poly_factor_array_free`].
 */
struct ocas_OcasPolyFactorArray {
  /**
   * Pointer to the first factor. May be `NULL` if `len == 0`.
   */
  struct ocas_OcasPolyFactor *factors;
  /**
   * Number of factors in the array.
   */
  size_t len;
};

/**
 * Opaque handle for a bivariate polynomial over a prime finite field.
 */
struct ocas_OcasPolyFp {
  uint8_t _private[0];
};

/**
 * Opaque handle for an algebraic number field $\mathbb{Q}(\alpha)$.
 */
struct ocas_OcasAlgebraicField {
  uint8_t _private[0];
};

/**
 * Opaque handle for a univariate polynomial over an algebraic number field.
 */
struct ocas_OcasAlgebraicPoly {
  uint8_t _private[0];
};

/**
 * A factor returned by [`ocas_algebraic_poly_factor`]. The `poly` pointer
 * must be cast to `OcasAlgebraicPoly*` and freed with
 * [`ocas_algebraic_poly_free`].
 */
struct ocas_OcasAlgebraicFactor {
  /**
   * The polynomial factor.
   */
  void *poly;
  /**
   * Multiplicity of the factor.
   */
  size_t multiplicity;
};

/**
 * An array of factors returned by [`ocas_algebraic_poly_factor`]. Free with
 * [`ocas_algebraic_factor_array_free`].
 */
struct ocas_OcasAlgebraicFactorArray {
  /**
   * Pointer to the first factor. May be `NULL` if `len == 0`.
   */
  struct ocas_OcasAlgebraicFactor *factors;
  /**
   * Number of factors in the array.
   */
  size_t len;
};

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Return the oCAS version string.
 *
 * The returned pointer is valid for the lifetime of the program and must
 * not be freed by the caller.
 */
const char *ocas_version(void);

/**
 * Return the message for the last error on the calling thread, or `NULL`
 * if no error has occurred.
 *
 * The returned string is owned by the library and must not be freed or
 * modified by the caller. It remains valid until the next call that sets
 * an error on the same thread or until [`ocas_error_clear`] is called.
 */
const char *ocas_error_last_message(void);

/**
 * Clear the last error on the calling thread.
 */
void ocas_error_clear(void);

/**
 * Parse `input` into a new expression handle.
 *
 * Returns `NULL` on failure; use [`ocas_error_last_message`](crate::ocas_error_last_message)
 * to retrieve the error message. On success, `*err_out` (if non-null) is
 * set to [`OCAS_OK`](crate::OCAS_OK).
 *
 * # Safety
 *
 * `input` must be a valid null-terminated C string. `err_out` if non-null
 * must point to writable memory.
 */
struct ocas_OcasExpr *ocas_expr_parse(const char *input, int *err_out);

/**
 * Free an expression handle. Passing `NULL` is a no-op.
 *
 * # Safety
 *
 * `handle` must be either null or a pointer returned by a function in this
 * module, and must not have been freed already.
 */
void ocas_expr_free(struct ocas_OcasExpr *handle);

/**
 * Clone an expression into a new arena.
 *
 * # Safety
 *
 * `handle` must be a valid non-null expression handle.
 */
struct ocas_OcasExpr *ocas_expr_clone(const struct ocas_OcasExpr *handle, int *err_out);

/**
 * Render `handle` to a null-terminated C string.
 *
 * The returned string is heap-allocated and owned by the caller. Release it
 * with [`ocas_string_free`]. Returns `NULL` on failure.
 *
 * # Safety
 *
 * `handle` must be a valid non-null expression handle.
 */
char *ocas_expr_to_string(const struct ocas_OcasExpr *handle, int *err_out);

/**
 * Free a string returned by [`ocas_expr_to_string`]. Passing `NULL` is a
 * no-op.
 *
 * # Safety
 *
 * `s` must be either null or a pointer returned by [`ocas_expr_to_string`],
 * and must not have been freed already.
 */
void ocas_string_free(char *s);

/**
 * Re-normalize `handle` in place.
 *
 * # Safety
 *
 * `handle` must be a valid non-null expression handle.
 */
int ocas_expr_normalize(struct ocas_OcasExpr *handle, int *err_out);

/**
 * Differentiate `handle` with respect to `var`. Returns a new expression
 * handle (caller owns it) or `NULL` on failure.
 *
 * # Safety
 *
 * `handle` must be a valid non-null expression handle. `var` must be a
 * valid null-terminated C string.
 */
struct ocas_OcasExpr *ocas_expr_diff(const struct ocas_OcasExpr *handle,
                                     const char *var,
                                     int *err_out);

/**
 * Integrate `handle` with respect to `var`. Returns a new expression handle
 * or `NULL` on failure. If the integral cannot be solved analytically, the
 * result is the unevaluated form `Integral(expr, var)`.
 *
 * # Safety
 *
 * See [`ocas_expr_diff`].
 */
struct ocas_OcasExpr *ocas_expr_integrate(const struct ocas_OcasExpr *handle,
                                          const char *var,
                                          int *err_out);

/**
 * Compute the Taylor series of `handle` around `point` up to `order`.
 *
 * # Safety
 *
 * `handle` and `point` must be valid non-null expression handles. `var`
 * must be a valid null-terminated C string.
 */
struct ocas_OcasExpr *ocas_expr_taylor(const struct ocas_OcasExpr *handle,
                                       const char *var,
                                       const struct ocas_OcasExpr *point,
                                       uint32_t order,
                                       int *err_out);

/**
 * Simplify `handle` using the default rule set. Returns a new expression
 * handle or `NULL` on failure.
 *
 * # Safety
 *
 * `handle` must be a valid non-null expression handle.
 */
struct ocas_OcasExpr *ocas_expr_simplify(const struct ocas_OcasExpr *handle, int *err_out);

/**
 * Substitute every occurrence of `var` in `handle` with `replacement`.
 *
 * # Safety
 *
 * `handle` and `replacement` must be valid non-null expression handles.
 * `var` must be a valid null-terminated C string.
 */
struct ocas_OcasExpr *ocas_expr_substitute(const struct ocas_OcasExpr *handle,
                                           const char *var,
                                           const struct ocas_OcasExpr *replacement,
                                           int *err_out);

/**
 * Create a bivariate integer polynomial from a string expression.
 *
 * The input may contain the variables `x` and `y`, integer coefficients,
 * addition, multiplication, and non-negative integer powers.
 *
 * Returns an opaque handle, or `NULL` on parse failure. On failure the
 * error message can be read with [`ocas_error_last_message`].
 */
struct ocas_OcasPolyZ *ocas_poly_z_create(const char *input, int *err);

/**
 * Free a polynomial handle created with [`ocas_poly_z_create`].
 */
void ocas_poly_z_free(struct ocas_OcasPolyZ *poly);

/**
 * Clone a polynomial handle. Returns a new handle that must be freed.
 */
struct ocas_OcasPolyZ *ocas_poly_z_clone(const struct ocas_OcasPolyZ *poly);

/**
 * Return the total degree of the polynomial, or `0` for the zero polynomial.
 */
size_t ocas_poly_z_degree(const struct ocas_OcasPolyZ *poly);

/**
 * Return a heap-allocated string representation of the polynomial.
 * The caller must release the returned string with [`ocas_string_free`].
 */
char *ocas_poly_z_to_string(const struct ocas_OcasPolyZ *poly, int *err);

/**
 * Factor a bivariate integer polynomial.
 *
 * On success, `out` is filled with a heap-allocated array of factors and
 * multiplicities. The caller must release it with
 * [`ocas_poly_factor_array_free`]. On failure `out` is unchanged and the
 * error message can be queried with [`ocas_error_last_message`].
 */
int ocas_poly_z_factor(const struct ocas_OcasPolyZ *poly,
                       struct ocas_OcasPolyFactorArray *out,
                       int *err);

/**
 * Create a bivariate polynomial over the prime field `F_p` from a string.
 *
 * `prime` is the field modulus (must be prime). Coefficients in the string
 * are reduced modulo `p`.
 */
struct ocas_OcasPolyFp *ocas_poly_fp_create(const char *input, const char *prime, int *err);

/**
 * Free a finite-field polynomial handle.
 */
void ocas_poly_fp_free(struct ocas_OcasPolyFp *poly);

/**
 * Clone a finite-field polynomial handle.
 */
struct ocas_OcasPolyFp *ocas_poly_fp_clone(const struct ocas_OcasPolyFp *poly);

/**
 * Return the total degree of the finite-field polynomial.
 */
size_t ocas_poly_fp_degree(const struct ocas_OcasPolyFp *poly);

/**
 * Return a heap-allocated string representation of the finite-field
 * polynomial. The caller must release it with [`ocas_string_free`].
 */
char *ocas_poly_fp_to_string(const struct ocas_OcasPolyFp *poly, int *err);

/**
 * Factor a bivariate polynomial over a prime finite field.
 */
int ocas_poly_fp_factor(const struct ocas_OcasPolyFp *poly,
                        struct ocas_OcasPolyFactorArray *out,
                        int *err);

/**
 * Free a factor array returned by [`ocas_poly_z_factor`] or
 * [`ocas_poly_fp_factor`].
 *
 * This frees the array structure and the `OcasPolyFactor` objects themselves,
 * but *not* the individual polynomial handles. The caller must free each
 * returned polynomial factor with the appropriate type-specific free function
 * (e.g. [`ocas_poly_z_free`] or [`ocas_poly_fp_free`]).
 */
void ocas_poly_factor_array_free(struct ocas_OcasPolyFactorArray *arr);

/**
 * Create an algebraic number field from its monic minimal polynomial.
 *
 * `min_poly` is a string such as `"x^2 - 2"` (variable must be `x`). Returns
 * an opaque handle, or `NULL` on failure.
 */
struct ocas_OcasAlgebraicField *ocas_algebraic_field_create(const char *min_poly, int *err);

/**
 * Free an algebraic number field handle.
 */
void ocas_algebraic_field_free(struct ocas_OcasAlgebraicField *field);

/**
 * Return the extension degree $\deg(m)$, or `0` on a null handle.
 */
size_t ocas_algebraic_field_degree(const struct ocas_OcasAlgebraicField *field);

/**
 * Create a polynomial over an algebraic number field from a coefficient-list
 * string (see the [module docs](self) for the format).
 */
struct ocas_OcasAlgebraicPoly *ocas_algebraic_poly_create(const struct ocas_OcasAlgebraicField *field,
                                                          const char *coeffs,
                                                          int *err);

/**
 * Free an algebraic-field polynomial handle.
 */
void ocas_algebraic_poly_free(struct ocas_OcasAlgebraicPoly *poly);

/**
 * Return the degree of the polynomial, or `0` for the zero polynomial.
 */
size_t ocas_algebraic_poly_degree(const struct ocas_OcasAlgebraicPoly *poly);

/**
 * Return a heap-allocated string representation of the polynomial.
 * The caller must release it with [`ocas_string_free`].
 */
char *ocas_algebraic_poly_to_string(const struct ocas_OcasAlgebraicPoly *poly, int *err);

/**
 * Factor a polynomial over an algebraic number field (Trager's algorithm).
 *
 * On success `out` is filled with a heap-allocated array of factors. The
 * caller must free each factor's `poly` via [`ocas_algebraic_poly_free`]
 * and then the array via [`ocas_algebraic_factor_array_free`].
 */
int ocas_algebraic_poly_factor(const struct ocas_OcasAlgebraicPoly *poly,
                               struct ocas_OcasAlgebraicFactorArray *out,
                               int *err);

/**
 * Free a factor array returned by [`ocas_algebraic_poly_factor`].
 *
 * This releases only the array storage; each factor's `poly` handle must be
 * freed separately via [`ocas_algebraic_poly_free`].
 */
void ocas_algebraic_factor_array_free(struct ocas_OcasAlgebraicFactorArray *arr);

/**
 * Opaque handle for a Vegas adaptive Monte Carlo integrator.
 */
struct ocas_OcasVegas {
  uint8_t _private[0];
};

/**
 * Result of a numerical integration: the estimate and its standard error.
 */
struct ocas_OcasIntegrateResult {
  /**
   * Best estimate of the integral.
   */
  double integral;
  /**
   * Estimated standard error on `integral`.
   */
  double error;
};

/**
 * Tuning knobs for [`ocas_vegas_create`]. Pass zeros (or `NULL` to the
 * creation function) to use library defaults.
 */
struct ocas_OcasVegasOptions {
  /**
   * Number of bins per dimension (default 64).
   */
  size_t n_bins;
  /**
   * Number of samples per iteration (default 10000).
   */
  size_t n_samples;
  /**
   * Number of adaptive iterations (default 10).
   */
  size_t iterations;
  /**
   * Grid smoothing / learning rate (default 1.5).
   */
  double learning_rate;
  /**
   * RNG seed (default 0x0C45).
   */
  uint64_t seed;
};

/**
 * Integrand function pointer for one-dimensional integration.
 *
 * `user_data` is passed through untouched from the caller of
 * [`ocas_vegas_integrate`] or [`ocas_integrate_1d`].
 */
typedef double (*ocas_integrand_t)(double x, void *user_data);

/**
 * Create a Vegas integrator for `n_dims` dimensions.
 *
 * `opts` may be `NULL` to use library defaults. Returns an opaque handle,
 * or `NULL` on failure (with the error code written to `*err`).
 */
struct ocas_OcasVegas *ocas_vegas_create(size_t n_dims,
                                         const struct ocas_OcasVegasOptions *opts,
                                         int *err);

/**
 * Free a Vegas integrator handle. Safe to call with `NULL`.
 */
void ocas_vegas_free(struct ocas_OcasVegas *v);

/**
 * Integrate `f` over the unit hypercube, invoking `f(x, user_data)` for each
 * sample. Returns the result; writes the error code to `*err` on failure.
 */
struct ocas_OcasIntegrateResult ocas_vegas_integrate(struct ocas_OcasVegas *v,
                                                     ocas_integrand_t f,
                                                     void *user_data,
                                                     int *err);

/**
 * Latest accumulated estimate and error after [`ocas_vegas_integrate`].
 */
struct ocas_OcasIntegrateResult ocas_vegas_result(const struct ocas_OcasVegas *v);

/**
 * Number of completed iterations, or `0` on a null handle.
 */
size_t ocas_vegas_iterations(const struct ocas_OcasVegas *v);

/**
 * Numerically integrate `f` over `[a, b]` using Vegas in one shot.
 *
 * `opts` may be `NULL` to use library defaults. Returns the result; writes
 * the error code to `*err` on failure.
 */
struct ocas_OcasIntegrateResult ocas_integrate_1d(ocas_integrand_t f,
                                                  void *user_data,
                                                  double a,
                                                  double b,
                                                  const struct ocas_OcasVegasOptions *opts,
                                                  int *err);

/**
 * Opaque handle for a tensor (named object with index slots).
 */
struct ocas_OcasTensor {
  uint8_t _private[0];
};

/**
 * Result of [`ocas_tensor_contract`]. When `kind == 0` (product), `tensors`
 * holds `n_tensors` independent tensor handles the caller must free via
 * [`ocas_tensor_free`]. When `kind == 1` (scalar), `scalar_str` holds a
 * heap-allocated string the caller must release via [`ocas_string_free`].
 */
struct ocas_OcasTensorContraction {
  /**
   * `0` = product, `1` = scalar.
   */
  int kind;
  /**
   * Array of `OcasTensor*` handles (valid when `kind == 0`). May be `NULL`.
   */
  struct ocas_OcasTensor **tensors;
  /**
   * Number of tensor handles in `tensors`.
   */
  size_t n_tensors;
  /**
   * Heap-allocated scalar string (valid when `kind == 1`). May be `NULL`.
   */
  char *scalar_str;
};

/**
 * Create a tensor from a name, a slots string, and an optional symmetry.
 *
 * `slots` is a semicolon-separated list of `label,position` entries where
 * `position` is `"upper"` or `"lower"` (aliases: `up`, `down`,
 * `contravariant`, `covariant`). Example: `"i,upper;j,lower"`.
 * `symmetry` may be `NULL` (meaning `"none"`) or one of `"none"`,
 * `"symmetric"`, `"antisymmetric"`.
 */
struct ocas_OcasTensor *ocas_tensor_create(const char *name,
                                           const char *slots,
                                           const char *symmetry,
                                           int *err);

/**
 * Free a tensor handle. Safe to call with `NULL`.
 */
void ocas_tensor_free(struct ocas_OcasTensor *t);

/**
 * Return the tensor's name as a heap-allocated string. The caller must
 * release it with [`ocas_string_free`].
 */
char *ocas_tensor_name(const struct ocas_OcasTensor *t, int *err);

/**
 * Return the tensor's arity (number of slots), or `0` on a null handle.
 */
size_t ocas_tensor_rank(const struct ocas_OcasTensor *t);

/**
 * Return the tensor's symmetry code: `0` = none, `1` = symmetric,
 * `2` = antisymmetric, `-1` on a null handle.
 */
int ocas_tensor_symmetry(const struct ocas_OcasTensor *t);

/**
 * Return a heap-allocated string representation of the tensor rendered as
 * `name(slot, slot, ...)`. The caller must release it with
 * [`ocas_string_free`].
 */
char *ocas_tensor_to_string(const struct ocas_OcasTensor *t, int *err);

/**
 * Return the symmetrisation sign of the tensor (+1 or -1), or `0` on a null
 * handle.
 */
int64_t ocas_tensor_symmetrise_sign(const struct ocas_OcasTensor *t);

/**
 * Contract two tensors by summing over shared dummy indices (equal label,
 * opposite variance). On success fills `out` (see
 * [`OcasTensorContraction`]).
 */
int ocas_tensor_contract(const struct ocas_OcasTensor *a,
                         const struct ocas_OcasTensor *b,
                         struct ocas_OcasTensorContraction *out,
                         int *err);

/**
 * Free the `tensors` array (but NOT the individual tensor handles) returned
 * by [`ocas_tensor_contract`] when `kind == 0`, plus the `scalar_str` when
 * `kind == 1`. Each tensor handle must still be freed separately via
 * [`ocas_tensor_free`]. Safe to call with `NULL`.
 */
void ocas_tensor_contraction_free(struct ocas_OcasTensorContraction *c);

/**
 * Opaque handle for a dual-number shape (derivative layout).
 */
struct ocas_OcasDualShape {
  uint8_t _private[0];
};

/**
 * Opaque handle for a hyper-dual number (value plus partial derivatives).
 */
struct ocas_OcasHyperDual {
  uint8_t _private[0];
};

/**
 * Build a first-order shape tracking one derivative per variable for
 * `n_vars` variables. Returns an opaque handle, or `NULL` on failure.
 */
struct ocas_OcasDualShape *ocas_dual_shape_new(size_t n_vars, int *err);

/**
 * Free a dual-number shape handle. Safe to call with `NULL`.
 */
void ocas_dual_shape_free(struct ocas_OcasDualShape *s);

/**
 * Return the number of differentiation variables, or `0` on a null handle.
 */
size_t ocas_dual_shape_n_vars(const struct ocas_OcasDualShape *s);

/**
 * Return the total number of components, or `0` on a null handle.
 */
size_t ocas_dual_shape_n_components(const struct ocas_OcasDualShape *s);

/**
 * Create an independent variable `x_i = value`. `coeff` is a coefficient
 * string `"num"` or `"num/den"`. Derivative is 1 w.r.t. variable `i`.
 */
struct ocas_OcasHyperDual *ocas_dual_variable(const struct ocas_OcasDualShape *shape,
                                              size_t i,
                                              const char *coeff,
                                              int *err);

/**
 * Create a constant dual number (all derivatives zero).
 */
struct ocas_OcasHyperDual *ocas_dual_constant(const struct ocas_OcasDualShape *shape,
                                              const char *coeff,
                                              int *err);

/**
 * Free a hyper-dual handle. Safe to call with `NULL`.
 */
void ocas_hyperdual_free(struct ocas_OcasHyperDual *d);

/**
 * Return the scalar value component as a heap-allocated string (`"num"` or
 * `"num/den"`). The caller must release it with [`ocas_string_free`].
 */
char *ocas_dual_value(const struct ocas_OcasHyperDual *d, int *err);

/**
 * Return the derivative w.r.t. variable `i` as a heap-allocated string, or
 * `NULL` if the shape has no first-order component for `i`.
 */
char *ocas_dual_deriv(const struct ocas_OcasHyperDual *d, size_t i, int *err);

/**
 * Compute `a + b` and return a new handle. Both operands must share a shape.
 */
struct ocas_OcasHyperDual *ocas_dual_add(const struct ocas_OcasHyperDual *a,
                                         const struct ocas_OcasHyperDual *b,
                                         int *err);

/**
 * Compute `a - b` and return a new handle.
 */
struct ocas_OcasHyperDual *ocas_dual_sub(const struct ocas_OcasHyperDual *a,
                                         const struct ocas_OcasHyperDual *b,
                                         int *err);

/**
 * Compute `a * b` and return a new handle.
 */
struct ocas_OcasHyperDual *ocas_dual_mul(const struct ocas_OcasHyperDual *a,
                                         const struct ocas_OcasHyperDual *b,
                                         int *err);

/**
 * Compute `a / b` and return a new handle. Sets an error if the divisor's
 * value component is zero.
 */
struct ocas_OcasHyperDual *ocas_dual_div(const struct ocas_OcasHyperDual *a,
                                         const struct ocas_OcasHyperDual *b,
                                         int *err);

/**
 * Compute `-a` (negation) and return a new handle.
 */
struct ocas_OcasHyperDual *ocas_dual_neg(const struct ocas_OcasHyperDual *a, int *err);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* OCAS_H */
